package enums

import model.dom.enums.DataType

enum class OperatorEnum(val type : Array<DataType>, val key : String, val operator: Array<String>) {
    EQUAL(DataType.values(), 
            "=", 
            arrayOf("equal")),
    NOT_EQUAL(DataType.values(), 
            "!=", 
            arrayOf("notEqual")),
    LESS_THAN(arrayOf(DataType.INTEGER, DataType.DOUBLE), 
            "<", 
            arrayOf("lessThan")),
    LESS_OR_EQUAL(arrayOf(DataType.INTEGER, DataType.DOUBLE), 
            "<=", 
            arrayOf("lessOrEqual")),
    GREATER_THAN(arrayOf(DataType.INTEGER, DataType.DOUBLE), 
            ">",
            arrayOf("greaterThan")),
    GREATER_OR_EQUAL(arrayOf(DataType.INTEGER, DataType.DOUBLE), 
            ">=", 
            arrayOf("greaterOrEqual")),
    IS_MISSING(DataType.values(),
            "missing",
            arrayOf("isMissing")),
    IS_NOT_MISSING(DataType.values(),
            "not missing",
            arrayOf("isNotMissing")),
    IS_IN(DataType.values(), 
            "in", 
            arrayOf("equal")),
    IS_NOT_IN(DataType.values(),
            "not in", 
            arrayOf("notEqual")),
    OPEN_OPEN(arrayOf(DataType.INTEGER, DataType.DOUBLE),
            ">..<", 
            arrayOf("greaterThan", "lessThan")),
    CLOSED_OPEN(arrayOf(DataType.INTEGER, DataType.DOUBLE),
            ">=..<", 
            arrayOf("greaterOrEqual", "lessThan")),
    OPEN_CLOSED(arrayOf(DataType.INTEGER, DataType.DOUBLE),
            ">..<=", 
            arrayOf("greaterThan", "lessOrEqual")),
    CLOSED_CLOSED(arrayOf(DataType.INTEGER, DataType.DOUBLE),
            ">=..<=", 
            arrayOf("greaterOrEqual", "lessOrEqual"));
}